export {
  adminCreateLesson,
  adminCreateProgram,
  adminCreateProgramLegacy,
  adminCreateWeek,
  adminDeleteLesson,
  adminDeleteWeek,
  adminGetNextLessonOrder,
  adminGrantProgramAccess,
  adminGrantProgramAccessLegacy,
  adminListLessons,
  adminListProgramAccessGrants,
  adminListWeeks,
  adminRevokeAccessGrant,
  adminSearchStudents,
  adminSetProgramPublished,
  adminUpdateLesson,
  adminUpdateProgram,
  adminUpdateWeek,
  getAdminProgramDetail,
  listAdminPrograms,
  listNutritionPlans,
  listStudentProfiles,
  listTrainingSlots,
  searchStudentProfiles,
  uploadLessonVideo,
  adminCreateNutritionPlan,
  adminCreateTrainingSlot,
  adminDeleteNutritionPlan,
  adminDeleteTrainingSlot,
} from './admin.service';
export type { AccessGrantWithUser } from './admin.service';
